name: "Google Java Format"
description: "Automatically format Java files using Google Java Style"
author: "axel-op"
branding:
  color: "red"
  icon: "align-right"
inputs:
  args:
    description: "Arguments for the Google Java Format executable"
    required: false
    default: "--replace"
  files:
    description: "Files to be formatted"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
